-- Using a format like this should enable a unique sample for every column, where each column will appear as a row with column_name and sample_value
WITH sampled_data AS (
  SELECT
    ARRAY_CONCAT(
      [STRUCT('hit_time_gmt' AS column_name, CAST(hit_time_gmt AS STRING) AS sample_value)],
      [STRUCT('visit_start_time_gmt' AS column_name, CAST(visit_start_time_gmt AS STRING) AS sample_value)],
      [STRUCT('channel' AS column_name, channel AS sample_value)],
      [STRUCT('clickmaplink' AS column_name, clickmaplink AS sample_value)],
      [STRUCT('evar3' AS column_name, evar3 AS sample_value)],
      [STRUCT('evar5' AS column_name, evar5 AS sample_value)],
      [STRUCT('post_evar5' AS column_name, post_evar5 AS sample_value)],
      [STRUCT('evar6' AS column_name, evar6 AS sample_value)],
      [STRUCT('post_evar6' AS column_name, post_evar6 AS sample_value)],
      [STRUCT('evar10' AS column_name, evar10 AS sample_value)],
      [STRUCT('post_evar10' AS column_name, post_evar10 AS sample_value)],
      [STRUCT('evar11' AS column_name, evar11 AS sample_value)],
      [STRUCT('post_evar11' AS column_name, post_evar11 AS sample_value)],
      [STRUCT('evar12' AS column_name, evar12 AS sample_value)],
      [STRUCT('post_evar12' AS column_name, post_evar12 AS sample_value)],
      [STRUCT('evar13' AS column_name, evar13 AS sample_value)],
      [STRUCT('evar21' AS column_name, evar21 AS sample_value)],
      [STRUCT('post_evar21' AS column_name, post_evar21 AS sample_value)],
      [STRUCT('evar24' AS column_name, evar24 AS sample_value)],
      [STRUCT('post_evar24' AS column_name, post_evar24 AS sample_value)],
      [STRUCT('evar25' AS column_name, evar25 AS sample_value)],
      [STRUCT('post_evar25' AS column_name, post_evar25 AS sample_value)],
      [STRUCT('evar26' AS column_name, evar26 AS sample_value)],
      [STRUCT('post_evar26' AS column_name, post_evar26 AS sample_value)],
      [STRUCT('post_evar28' AS column_name, post_evar28 AS sample_value)],
      [STRUCT('evar29' AS column_name, evar29 AS sample_value)],
      [STRUCT('post_evar29' AS column_name, post_evar29 AS sample_value)],
      [STRUCT('evar32' AS column_name, evar32 AS sample_value)],
      [STRUCT('evar33' AS column_name, evar33 AS sample_value)],
      [STRUCT('evar37' AS column_name, evar37 AS sample_value)],
      [STRUCT('evar38' AS column_name, evar38 AS sample_value)],
      [STRUCT('evar39' AS column_name, evar39 AS sample_value)],
      [STRUCT('post_evar39' AS column_name, post_evar39 AS sample_value)],
      [STRUCT('evar41' AS column_name, evar41 AS sample_value)],
      [STRUCT('post_evar41' AS column_name, post_evar41 AS sample_value)],
      [STRUCT('evar45' AS column_name, evar45 AS sample_value)],
      [STRUCT('post_evar45' AS column_name, post_evar45 AS sample_value)],
      [STRUCT('evar53' AS column_name, evar53 AS sample_value)],
      [STRUCT('post_evar53' AS column_name, post_evar53 AS sample_value)],
      [STRUCT('evar59' AS column_name, evar59 AS sample_value)],
      [STRUCT('post_evar59' AS column_name, post_evar59 AS sample_value)],
      [STRUCT('evar63' AS column_name, evar63 AS sample_value)],
      [STRUCT('evar67' AS column_name, evar67 AS sample_value)],
      [STRUCT('evar68' AS column_name, evar68 AS sample_value)],
      [STRUCT('evar69' AS column_name, evar69 AS sample_value)],
      [STRUCT('evar70' AS column_name, evar70 AS sample_value)],
      [STRUCT('evar72' AS column_name, evar72 AS sample_value)],
      [STRUCT('evar73' AS column_name, evar73 AS sample_value)],
      [STRUCT('evar75' AS column_name, evar75 AS sample_value)],
      [STRUCT('evar76' AS column_name, evar76 AS sample_value)],
      [STRUCT('evar80' AS column_name, evar80 AS sample_value)],
      [STRUCT('evar83' AS column_name, evar83 AS sample_value)],
      [STRUCT('evar95' AS column_name, evar95 AS sample_value)],
      [STRUCT('evar99' AS column_name, evar99 AS sample_value)],
      [STRUCT('evar111' AS column_name, evar111 AS sample_value)],
      [STRUCT('evar113' AS column_name, evar113 AS sample_value)],
      [STRUCT('evar116' AS column_name, evar116 AS sample_value)],
      [STRUCT('evar118' AS column_name, evar118 AS sample_value)],
      [STRUCT('evar154' AS column_name, evar154 AS sample_value)],
      [STRUCT('event_list' AS column_name, event_list AS sample_value)],
      [STRUCT('exclude_hit' AS column_name, CAST(exclude_hit AS STRING) AS sample_value)],
      [STRUCT('first_hit_page_url' AS column_name, first_hit_page_url AS sample_value)],
      [STRUCT('geo_city' AS column_name, geo_city AS sample_value)],
      [STRUCT('geo_country' AS column_name, geo_country AS sample_value)],
      [STRUCT('geo_dma' AS column_name, CAST(geo_dma AS STRING) AS sample_value)],
      [STRUCT('geo_region' AS column_name, geo_region AS sample_value)],
      [STRUCT('geo_zip' AS column_name, geo_zip AS sample_value)],
      [STRUCT('post_evar52' AS column_name, post_evar52 AS sample_value)],
      [STRUCT('hit_source' AS column_name, CAST(hit_source AS STRING) AS sample_value)],
      [STRUCT('ip' AS column_name, ip AS sample_value)],
      [STRUCT('mobile_id' AS column_name, mobile_id AS sample_value)],
      [STRUCT('mobileappid' AS column_name, mobileappid AS sample_value)],
      [STRUCT('mvvar1' AS column_name, mvvar1 AS sample_value)],
      [STRUCT('mvvar2' AS column_name, mvvar2 AS sample_value)],
      [STRUCT('mvvar3' AS column_name, mvvar3 AS sample_value)],
      [STRUCT('page_event_var2' AS column_name, page_event_var2 AS sample_value)],
      [STRUCT('page_url' AS column_name, page_url AS sample_value)],
      [STRUCT('pagename' AS column_name, pagename AS sample_value)],
      [STRUCT('post_channel' AS column_name, post_channel AS sample_value)],
      [STRUCT('post_evar1' AS column_name, post_evar1 AS sample_value)],
      [STRUCT('post_evar2' AS column_name, post_evar2 AS sample_value)],
      [STRUCT('post_evar3' AS column_name, post_evar3 AS sample_value)],
      [STRUCT('post_evar4' AS column_name, post_evar4 AS sample_value)],
      [STRUCT('post_evar8' AS column_name, post_evar8 AS sample_value)],
      [STRUCT('post_evar17' AS column_name, post_evar17 AS sample_value)],
      [STRUCT('post_evar30' AS column_name, post_evar30 AS sample_value)],
      [STRUCT('post_evar54' AS column_name, post_evar54 AS sample_value)],
      [STRUCT('post_evar55' AS column_name, post_evar55 AS sample_value)],
      [STRUCT('post_evar63' AS column_name, post_evar63 AS sample_value)],
      [STRUCT('post_evar64' AS column_name, post_evar64 AS sample_value)],
      [STRUCT('post_evar70' AS column_name, post_evar70 AS sample_value)],
      [STRUCT('post_evar71' AS column_name, post_evar71 AS sample_value)],
      [STRUCT('post_evar72' AS column_name, post_evar72 AS sample_value)],
      [STRUCT('post_evar73' AS column_name, post_evar73 AS sample_value)],
      [STRUCT('post_evar74' AS column_name, post_evar74 AS sample_value)],
      [STRUCT('post_evar76' AS column_name, post_evar76 AS sample_value)],
      [STRUCT('post_evar79' AS column_name, post_evar79 AS sample_value)],
      [STRUCT('post_evar80' AS column_name, post_evar80 AS sample_value)],
      [STRUCT('post_evar81' AS column_name, post_evar81 AS sample_value)],
      [STRUCT('post_evar83' AS column_name, post_evar83 AS sample_value)],
      [STRUCT('post_evar84' AS column_name, post_evar84 AS sample_value)],
      [STRUCT('post_evar88' AS column_name, post_evar88 AS sample_value)],
      [STRUCT('post_evar90' AS column_name, post_evar90 AS sample_value)],
      [STRUCT('post_evar91' AS column_name, post_evar91 AS sample_value)],
      [STRUCT('post_evar93' AS column_name, post_evar93 AS sample_value)],
      [STRUCT('post_evar95' AS column_name, post_evar95 AS sample_value)],
      [STRUCT('post_evar110' AS column_name, post_evar110 AS sample_value)],
      [STRUCT('post_evar111' AS column_name, post_evar111 AS sample_value)],
      [STRUCT('post_evar112' AS column_name, post_evar112 AS sample_value)],
      [STRUCT('post_evar113' AS column_name, post_evar113 AS sample_value)],
      [STRUCT('post_evar116' AS column_name, post_evar116 AS sample_value)],
      [STRUCT('post_evar117' AS column_name, post_evar117 AS sample_value)],
      [STRUCT('post_evar118' AS column_name, post_evar118 AS sample_value)],
      [STRUCT('post_evar135' AS column_name, post_evar135 AS sample_value)],
      [STRUCT('post_evar140' AS column_name, post_evar140 AS sample_value)],
      [STRUCT('post_evar142' AS column_name, post_evar142 AS sample_value)],
      [STRUCT('post_evar147' AS column_name, post_evar147 AS sample_value)],
      [STRUCT('post_evar154' AS column_name, post_evar154 AS sample_value)],
      [STRUCT('post_evar166' AS column_name, post_evar166 AS sample_value)],
      [STRUCT('post_event_list' AS column_name, post_event_list AS sample_value)],
      [STRUCT('post_mobileappid' AS column_name, post_mobileappid AS sample_value)],
      [STRUCT('post_mvvar1' AS column_name, post_mvvar1 AS sample_value)],
      [STRUCT('post_mvvar2' AS column_name, post_mvvar2 AS sample_value)],
      [STRUCT('post_mvvar3' AS column_name, post_mvvar3 AS sample_value)],
      [STRUCT('post_page_event' AS column_name, CAST(post_page_event AS STRING) AS sample_value)],
      [STRUCT('post_page_event_var1' AS column_name, post_page_event_var1 AS sample_value)],
      [STRUCT('post_page_event_var2' AS column_name, post_page_event_var2 AS sample_value)],
      [STRUCT('post_page_event_var3' AS column_name, post_page_event_var3 AS sample_value)],
      [STRUCT('post_pagename' AS column_name, post_pagename AS sample_value)],
      [STRUCT('post_prop1' AS column_name, post_prop1 AS sample_value)],
      [STRUCT('post_prop2' AS column_name, post_prop2 AS sample_value)],
      [STRUCT('post_prop3' AS column_name, post_prop3 AS sample_value)],
      [STRUCT('post_prop4' AS column_name, post_prop4 AS sample_value)],
      [STRUCT('post_prop5' AS column_name, post_prop5 AS sample_value)],
      [STRUCT('post_prop6' AS column_name, post_prop6 AS sample_value)],
      [STRUCT('post_prop7' AS column_name, post_prop7 AS sample_value)],
      [STRUCT('post_prop8' AS column_name, post_prop8 AS sample_value)],
      [STRUCT('post_prop9' AS column_name, post_prop9 AS sample_value)],
      [STRUCT('post_prop10' AS column_name, post_prop10 AS sample_value)],
      [STRUCT('post_prop11' AS column_name, post_prop11 AS sample_value)],
      [STRUCT('post_prop12' AS column_name, post_prop12 AS sample_value)],
      [STRUCT('post_prop13' AS column_name, post_prop13 AS sample_value)],
      [STRUCT('post_prop14' AS column_name, post_prop14 AS sample_value)],
      [STRUCT('post_prop15' AS column_name, post_prop15 AS sample_value)],
      [STRUCT('post_prop16' AS column_name, post_prop16 AS sample_value)],
      [STRUCT('post_prop17' AS column_name, post_prop17 AS sample_value)],
      [STRUCT('post_prop18' AS column_name, post_prop18 AS sample_value)],
      [STRUCT('post_prop19' AS column_name, post_prop19 AS sample_value)],
      [STRUCT('post_prop20' AS column_name, post_prop20 AS sample_value)],
      [STRUCT('post_prop21' AS column_name, post_prop21 AS sample_value)],
      [STRUCT('post_prop22' AS column_name, post_prop22 AS sample_value)],
      [STRUCT('post_prop23' AS column_name, post_prop23 AS sample_value)],
      [STRUCT('post_prop24' AS column_name, post_prop24 AS sample_value)],
      [STRUCT('post_prop25' AS column_name, post_prop25 AS sample_value)],
      [STRUCT('post_prop26' AS column_name, post_prop26 AS sample_value)],
      [STRUCT('post_prop27' AS column_name, post_prop27 AS sample_value)],
      [STRUCT('post_prop50' AS column_name, post_prop50 AS sample_value)],
      [STRUCT('post_prop64' AS column_name, post_prop64 AS sample_value)],
      [STRUCT('post_prop65' AS column_name, post_prop65 AS sample_value)],
      [STRUCT('post_prop72' AS column_name, post_prop72 AS sample_value)],
      [STRUCT('post_purchaseid' AS column_name, post_purchaseid AS sample_value)],
      [STRUCT('post_referrer' AS column_name, post_referrer AS sample_value)],
      [STRUCT('post_visid_high' AS column_name, CAST(post_visid_high AS STRING) AS sample_value)],
      [STRUCT('post_visid_low' AS column_name, CAST(post_visid_low AS STRING) AS sample_value)],
      [STRUCT('prop1' AS column_name, prop1 AS sample_value)],
      [STRUCT('prop5' AS column_name, prop5 AS sample_value)],
      [STRUCT('prop6' AS column_name, prop6 AS sample_value)],
      [STRUCT('prop10' AS column_name, prop10 AS sample_value)],
      [STRUCT('prop11' AS column_name, prop11 AS sample_value)],
      [STRUCT('purchaseid' AS column_name, purchaseid AS sample_value)],
      [STRUCT('ref_domain' AS column_name, ref_domain AS sample_value)],
      [STRUCT('ref_type' AS column_name, CAST(ref_type AS STRING) AS sample_value)],
      [STRUCT('referrer' AS column_name, referrer AS sample_value)],
      [STRUCT('search_page_num' AS column_name, CAST(search_page_num AS STRING) AS sample_value)],
      [STRUCT('user_agent' AS column_name, user_agent AS sample_value)],
      [STRUCT('user_server' AS column_name, user_server AS sample_value)],
      [STRUCT('visit_keywords' AS column_name, visit_keywords AS sample_value)],
      [STRUCT('visit_num' AS column_name, CAST(visit_num AS STRING) AS sample_value)],
      [STRUCT('visit_page_num' AS column_name, CAST(visit_page_num AS STRING) AS sample_value)],
      [STRUCT('visit_ref_type' AS column_name, CAST(visit_ref_type AS STRING) AS sample_value)],
      [STRUCT('visit_referrer' AS column_name, visit_referrer AS sample_value)],
      [STRUCT('visit_ref_domain' AS column_name, visit_ref_domain AS sample_value)],
      [STRUCT('visit_search_engine' AS column_name, CAST(visit_search_engine AS STRING) AS sample_value)],
      [STRUCT('visit_start_page_url' AS column_name, visit_start_page_url AS sample_value)],
      [STRUCT('visit_start_pagename' AS column_name, visit_start_pagename AS sample_value)],
      [STRUCT('zip' AS column_name, zip AS sample_value)],
      [STRUCT('cycle_date' AS column_name, CAST(cycle_date AS STRING) AS sample_value)]
    ) AS samples
  FROM djomniture.cipomniture_hourly_djglobal.2025_02
  LIMIT 1
)
SELECT column_name, sample_value
FROM sampled_data
CROSS JOIN UNNEST(samples)
WHERE sample_value IS NOT NULL;
