--Basic Create Warehouse Command
CREATE WAREHOUSE CDL_X_SMALL_WH
  WAREHOUSE_TYPE = STANDARD
  WAREHOUSE_SIZE = XSMALL
  MAX_CLUSTER_COUNT = 1
  MIN_CLUSTER_COUNT = 1
  SCALING_POLICY = STANDARD
  AUTO_SUSPEND = 30
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Generic X-Small warehouse for customer data lake';
